#!/bin/bash
cp -a "/root/wine-git" "/root/wine-tools"

####### Build Tools
cd "/root/wine-tools"
./configure
make __tooldeps__ -j 4
cd "tools/winebuild"
mv "winebuild" "winebuild.real"
echo '#!/bin/bash' > winebuild
echo "$PWD/winebuild.real -m32 \"\$@\"" >> winebuild
chmod +x winebuild

####### Build wine
cd "/root/wine-git"
## Environment preparation
export FRAMEWORK="10.8"
export CC="clang -target i386-apple-darwin12 -mlinker-version=0.0 -mmacosx-version-min=$FRAMEWORK -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/"

## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/i386-apple-darwin12-gcc"
chmod +x "/root/osxcross/target/bin/i386-apple-darwin12-gcc"

## Some tools are not directly found by wine
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ld" "/root/osxcross/target/bin/ld"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-otool" "/root/osxcross/target/bin/otool"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ranlib" "/root/osxcross/target/bin/ranlib"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ar" "/root/osxcross/target/bin/ar"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-as" "/root/osxcross/target/bin/as"

./configure --host i386-apple-darwin12 --prefix="/" --with-wine-tools="/root/wine-tools" LFFLAGS=" -Wl,-rpath,/opt/x11/lib -L/root/osxcross/target/macports/pkgs/opt/local/lib -m32"
make -j 4
make install DESTDIR="/root/wine"

## Copying libs
cp /root/osxcross/target/macports/pkgs/opt/local/lib/*.dylib "/root/wine/lib"

## To make package smaller, we are only going to keep i386 part of the libraries
cd "/root/wine/lib/"
for file in *.dylib; do
  [ ! -L "$file" ] && i386-apple-darwin12-lipo -extract i386 "$file" -o "$file" 2> /dev/null
done
