#!/bin/bash
cd "/root/wine-git"
./configure --prefix="/"
make -j 4
make install DESTDIR="/root/wine"

mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"

### 64bits build
cd "/root/wine-git/wine64-build/"
../configure --enable-win64 --prefix="/"
make -j 4

### 32bits build
cd "/root/wine-git/wine32-build/"
../configure --with-wine64=/root/wine-git/wine64-build --prefix="/"
make -j 4

cd "/root/wine-git/wine64-build/"
make install DESTDIR="/root/wine"
cd "/root/wine-git/wine32-build/"
make install DESTDIR="/root/wine"
