#!/bin/bash
cp -a "/root/wine-git" "/root/wine-tools" || exit 1

####### Build Tools
echo "[STAGE 1/10] Configure tools"
cd "/root/wine-tools"
./configure || exit 2

echo "[STAGE 2/10] Make tools"
make __tooldeps__ -j 4 || exit 3
cd "tools/winebuild"
mv "winebuild" "winebuild.real"
echo '#!/bin/bash' > winebuild
echo "$PWD/winebuild.real -m32 \"\$@\"" >> winebuild
chmod +x winebuild



####### Build wine
### Environment preparation
mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"
export FRAMEWORK="10.11"

## Some tools are not directly found by wine
ln -s "/root/osxcross/target/bin/i386-apple-darwin15-ld" "/root/osxcross/target/bin/ld"
ln -s "/root/osxcross/target/bin/i386-apple-darwin15-otool" "/root/osxcross/target/bin/otool"
ln -s "/root/osxcross/target/bin/i386-apple-darwin15-ranlib" "/root/osxcross/target/bin/ranlib"
ln -s "/root/osxcross/target/bin/i386-apple-darwin15-ar" "/root/osxcross/target/bin/ar"
ln -s "/root/osxcross/target/bin/i386-apple-darwin15-as" "/root/osxcross/target/bin/as"


#### 64bits
export CC="clang -O3 -target x86_64-apple-darwin15 -mlinker-version=0.0 -mmacosx-version-min=10.8 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/  -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks"
## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/x86_64-apple-darwin15-gcc"
chmod +x "/root/osxcross/target/bin/x86_64-apple-darwin15-gcc"

####### Install VKD3D
echo "[STAGE 3/10] Installing vkd3d"
bash "/root/install_vkd3d.sh" "vkd3d-1.1" || exit 4

export C_INCLUDE_PATH="/root/osxcross/target/macports/pkgs/opt/local/include/:/root/osxcross/target/macports/pkgs/opt/local/include/libxml2/:/root/vkd3d/include/"
export LIBRARY_PATH="/root/osxcross/target/macports/pkgs/opt/local/lib"

cd "/root/wine-git/wine64-build/"
echo "[STAGE 4/10] Configure 64 bits"
../configure --enable-win64 --host x86_64-apple-darwin15 --prefix="/" --with-wine-tools="/root/wine-tools" LFFLAGS=" -Wl,-rpath,/opt/x11/lib -L/root/osxcross/target/macports/pkgs/opt/local/lib -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks" || exit 5
echo "[STAGE 5/10] Make 64 bits"
make -j 4 || exit 6

#### 32bits
export CC="clang -O3 -target i386-apple-darwin15 -mlinker-version=0.0 -mmacosx-version-min=10.8 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/ -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks"
## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/i386-apple-darwin15-gcc"
chmod +x "/root/osxcross/target/bin/i386-apple-darwin15-gcc"

cd "/root/wine-git/wine32-build/"
echo "[STAGE 6/10] Configure 32 bits"
../configure --with-wine64=/root/wine-git/wine64-build --host i386-apple-darwin15 --prefix="/" --with-wine-tools="/root/wine-tools" LFFLAGS=" -Wl,-rpath,/opt/x11/lib -L/root/osxcross/target/macports/pkgs/opt/local/lib" || exit 7

echo "[STAGE 7/10] Make 32 bits"
make -j 4 || exit 8

echo "[STAGE 8/10] Make install 64 bits"
cd "/root/wine-git/wine64-build/"
make install DESTDIR="/root/wine" || exit 9

echo "[STAGE 9/10] Make install 32 bits"
cd "/root/wine-git/wine32-build/"
make install DESTDIR="/root/wine" || exit 10

## Copying libs
echo "[STAGE 10/10] Copying libs"
cp /root/osxcross/target/macports/pkgs/opt/local/lib/*.dylib "/root/wine/lib"
echo "[END]"