#!/bin/bash
/etc/init.d/docker start
cd "/root/"
./steam-runtime/setup_docker.sh --beta amd64 --extra-bootstrap=./proton-git/steamrt-bootstrap.sh steam-proton-dev
./steam-runtime/setup_docker.sh --beta i386 --extra-bootstrap=./proton-git/steamrt-bootstrap.sh steam-proton-dev32

mkdir -p "/root/proton"
cd "/root/proton"
../configure.sh --steam-runtime64=docker:steam-proton-dev --steam-runtime32=docker:steam-proton-dev32
make -j6 all dist