#!/bin/bash
export CFLAGS="-O3"
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib/"

cd "/root/wine-git"
echo "[STAGE 1/4] Configure"
./configure --prefix="/" LDFLAGS="-L/usr/local/lib" || exit 1

echo "[STAGE 2/4] Make"
numberOfSteps="$(make __builddeps__ --no-print-directory -nrRk 2> /dev/null|wc -l)"
make __builddeps__ -j 4 | awk "{print \"[STEP \" NR \"/$numberOfSteps] \" \$s}" || exit 2

echo "[STAGE 3/4] Make"
numberOfSteps="$(make --no-print-directory -nrRk 2> /dev/null|wc -l)"
make -j 4 | awk "{print \"[STEP \" NR \"/$numberOfSteps] \" \$s}" || exit 3

echo "[STAGE 4/4] Make install"
make install DESTDIR="/root/wine" || exit 4
echo "[END]"