#!/bin/bash
cp -a "/root/wine-git" "/root/wine-tools" || exit 1

####### Build Tools
echo "[STAGE 1/10] Configure tools"
cd "/root/wine-tools"
./configure CC="clang" CXX="clang++" --disable-option-checking --disable-tests --without-unwind --enable-win64 >>/dev/null 2>&1 || exit 2

echo "[STAGE 2/10] Make tools"
make __tooldeps__ -j 4  >>/dev/null 2>&1 || exit 3

####### Build wine
mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"

####### Install VKD3D
#echo "[STAGE 3/11] Installing vkd3d"
#bash "/root/install_vkd3d.sh" "$VKD3D"  >>/dev/null 2>&1 || exit 4

### Environment preparation
export LDFLAGS="-Wl,-rpath,@loader_path/../ -Wl,-rpath,/opt/local/lib -Wl,-rpath,/opt/X11/lib"

#### Linux only options to disable
export LINUX_OPTIONS="--without-pulse --without-inotify --without-v4l2 --without-oss --without-udev --without-capi"

#### Cache gnutls_cipher check, fixed wine-5.8
# https://github.com/wine-mirror/wine/commit/7e0e556726deff3c93b2172de15cc1c523571b59
export ac_cv_func_gnutls_cipher_init="yes"

#### 64bit
cd "/root/wine-git/wine64-build/"
echo "[STAGE 3/10] Configure 64bit"
../configure --host x86_64-apple-darwin17 --disable-option-checking --disable-tests --without-unwind --enable-win64 --prefix="" --with-wine-tools="/root/wine-tools" ${LINUX_OPTIONS} || exit 5
echo "[STAGE 4/10] Make 64bit"
make -j 4 || exit 6

#### 32bit
cd "/root/wine-git/wine32-build/"
echo "[STAGE 5/10] Configure 32bit"
../configure --host i386-apple-darwin17 --disable-option-checking --disable-tests  --without-unwind TARGETFLAGS="-m32" --with-wine64=/root/wine-git/wine64-build --prefix="" --with-wine-tools="/root/wine-tools" ${LINUX_OPTIONS} || exit 7
echo "[STAGE 6/10] Make 32bit"
make -j 4 || exit 8

echo "[STAGE 7/10] Make install 32bit"
cd "/root/wine-git/wine32-build/"
make install-lib DESTDIR="/root/wine" || exit 9

echo "[STAGE 8/10] Make install 64bit"
cd "/root/wine-git/wine64-build/"
make install-lib DESTDIR="/root/wine" || exit 10

## Remove all the XQuartz files, not needed and shrink file size!
cd "/opt/local/lib"
rm libGL.1.dylib
rm libGL.dylib
rm libGLESv1_CM.1.dylib
rm libGLESv1_CM.dylib
rm libGLESv2.2.dylib
rm libGLESv2.dylib
rm libGLU.1.dylib
rm libGLU.dylib
rm libICE.6.dylib
rm libICE.dylib
rm libOSMesa.8.dylib
rm libOSMesa.dylib
rm libSM.6.dylib
rm libSM.dylib
rm libX11-xcb.1.dylib
rm libX11-xcb.dylib
rm libX11.6.dylib
rm libX11.dylib
rm libXau.6.dylib
rm libXau.dylib
rm libXcomposite.1.dylib
rm libXcomposite.dylib
rm libXcursor.1.dylib
rm libXcursor.dylib
rm libXdamage.1.dylib
rm libXdamage.dylib
rm libXdmcp.6.dylib
rm libXdmcp.dylib
rm libXext.6.dylib
rm libXext.dylib
rm libXfixes.3.dylib
rm libXfixes.dylib
rm libXft.2.dylib
rm libXft.dylib
rm libXi.6.dylib
rm libXi.dylib
rm libXinerama.1.dylib
rm libXinerama.dylib
rm libXmu.6.dylib
rm libXmu.dylib
rm libXmuu.1.dylib
rm libXmuu.dylib
rm libXrandr.2.dylib
rm libXrandr.dylib
rm libXrender.1.dylib
rm libXrender.dylib
rm libXt.6.dylib
rm libXt.dylib
rm libXv.1.dylib
rm libXv.dylib
rm libXxf86vm.1.dylib
rm libXxf86vm.dylib
rm libcairo-gobject.2.dylib
rm libcairo-gobject.dylib
rm libcairo-script-interpreter.2.dylib
rm libcairo-script-interpreter.dylib
rm libcairo.2.dylib
rm libcairo.dylib
rm libglapi.0.dylib
rm libglapi.dylib
rm libpixman-1.0.dylib
rm libpixman-1.dylib
rm libxcb-composite.0.dylib
rm libxcb-composite.dylib
rm libxcb-damage.0.dylib
rm libxcb-damage.dylib
rm libxcb-dpms.0.dylib
rm libxcb-dpms.dylib
rm libxcb-dri2.0.dylib
rm libxcb-dri2.dylib
rm libxcb-dri3.0.dylib
rm libxcb-dri3.dylib
rm libxcb-glx.0.dylib
rm libxcb-glx.dylib
rm libxcb-present.0.dylib
rm libxcb-present.dylib
rm libxcb-randr.0.dylib
rm libxcb-randr.dylib
rm libxcb-record.0.dylib
rm libxcb-record.dylib
rm libxcb-render.0.dylib
rm libxcb-render.dylib
rm libxcb-res.0.dylib
rm libxcb-res.dylib
rm libxcb-screensaver.0.dylib
rm libxcb-screensaver.dylib
rm libxcb-shape.0.dylib
rm libxcb-shape.dylib
rm libxcb-shm.0.dylib
rm libxcb-shm.dylib
rm libxcb-sync.1.dylib
rm libxcb-sync.dylib
rm libxcb-util.1.dylib
rm libxcb-util.dylib
rm libxcb-xf86dri.0.dylib
rm libxcb-xf86dri.dylib
rm libxcb-xfixes.0.dylib
rm libxcb-xfixes.dylib
rm libxcb-xinerama.0.dylib
rm libxcb-xinerama.dylib
rm libxcb-xinput.0.dylib
rm libxcb-xinput.dylib
rm libxcb-xkb.1.dylib
rm libxcb-xkb.dylib
rm libxcb-xtest.0.dylib
rm libxcb-xtest.dylib
rm libxcb-xv.0.dylib
rm libxcb-xv.dylib
rm libxcb-xvmc.0.dylib
rm libxcb-xvmc.dylib
rm libxcb.1.dylib
rm libxcb.dylib

## Fixing imports
echo "[STAGE 9/10] Fixing imports"
bash /root/fix_imports.sh "/opt/local" >>/dev/null 2>&1

## Copying libs
echo "[STAGE 10/10] Copying libs"

## Pre wine-6.8
if [ -d "/root/wine/lib/wine/fakedlls" ]; then
    cp -d /opt/local/lib/*.dylib "/root/wine/lib"
    cp -d /opt/local/lib/*.dylib "/root/wine/lib64"

    ## Make the dylibs 32Bit only
    cd "/root/wine/lib/"
    rm libMoltenVK.dylib
    for file in *.dylib; do
        [ ! -L "$file" ] && i386-apple-darwin17-lipo -thin i386 "$file" -o "$file" 2> /dev/null
    done
    ## Make the dylibs 64Bit only
    cd "/root/wine/lib64/"
    for file in *.dylib; do
        [ ! -L "$file" ] && x86_64-apple-darwin17-lipo -thin x86_64 "$file" -o "$file" 2> /dev/null
    done
else
    cp -d /opt/local/lib/*.dylib "/root/wine/lib"
fi

echo "[END]"
