#!/bin/bash
echo "[STAGE 1/7] Duplicating wine sources"
cp -a "/root/wine-git" "/root/wine-tools" || exit 1

####### Build Tools
echo "[STAGE 2/7]  Configure tools"
cd "/root/wine-tools"
./configure || exit 2

echo "[STAGE 3/7] Make tools"
numberOfSteps="$(make __tooldeps__ --no-print-directory -nrRk 2> /dev/null|wc -l)"
make __tooldeps__ -j 4 | awk "{print \"[STEP \" NR \"/$numberOfSteps] \" \$s}" || exit 3
cd "tools/winebuild"
mv "winebuild" "winebuild.real"
echo '#!/bin/bash' > winebuild
echo "$PWD/winebuild.real -m32 \"\$@\"" >> winebuild
chmod +x winebuild

####### Build wine
cd "/root/wine-git"
## Environment preparation
export FRAMEWORK="10.8"
export CC="clang -O3 -target i386-apple-darwin12 -mmacosx-version-min=$FRAMEWORK -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/ -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks/"

## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/i386-apple-darwin12-gcc"
chmod +x "/root/osxcross/target/bin/i386-apple-darwin12-gcc"

## Some tools are not directly found by wine
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ld" "/root/osxcross/target/bin/ld"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-otool" "/root/osxcross/target/bin/otool"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ranlib" "/root/osxcross/target/bin/ranlib"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-ar" "/root/osxcross/target/bin/ar"
ln -s "/root/osxcross/target/bin/i386-apple-darwin12-as" "/root/osxcross/target/bin/as"

echo "[STAGE 4/7] Configure"

./configure --host i386-apple-darwin12 --prefix="/" --with-wine-tools="/root/wine-tools" LFFLAGS=" -Wl,-rpath,/opt/x11/lib -L/root/osxcross/target/macports/pkgs/opt/local/lib -m32" || exit 4

echo "[STAGE 5/7] Make"
numberOfSteps="$(make __builddeps__ --no-print-directory -nrRk 2> /dev/null|wc -l)"
make __builddeps__ -j 4 | awk "{print \"[STEP \" NR \"/$numberOfSteps] \" \$s}" || exit 5

echo "[STAGE 6/7] Make"
numberOfSteps="$(make --no-print-directory -nrRk 2> /dev/null|wc -l)"
make -j 4 | awk "{print \"[STEP \" NR \"/$numberOfSteps] \" \$s}" || exit 6

echo "[STAGE 7/7] Make install"
make install DESTDIR="/root/wine" || exit 7

## Copying libs
cp /root/osxcross/target/macports/pkgs/opt/local/lib/*.dylib "/root/wine/lib"

## To make package smaller, we are only going to keep i386 part of the libraries
cd "/root/wine/lib/"
for file in *.dylib; do
  [ ! -L "$file" ] && i386-apple-darwin12-lipo -extract i386 "$file" -o "$file" 2> /dev/null
done

echo "[END]"
