#!/bin/bash
cp -a "/root/wine-git" "/root/wine-tools" || exit 1

####### Build Tools
apt-get -y install libfreetype6-dev:i386
apt-get -y install libx11-dev:i386
echo "[STAGE 1/11] Configure tools"
cd "/root/wine-tools"
./configure  || exit 2

echo "[STAGE 2/11] Make tools"
make __tooldeps__ -j 4 || exit 3
cd "tools/winebuild"
mv "winebuild" "winebuild.real"
echo '#!/bin/bash' > winebuild
echo "$PWD/winebuild.real -m32 \"\$@\"" >> winebuild
chmod +x winebuild

####### Build wine
apt-get -y install libfreetype6-dev
### Environment preparation
mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"
export FRAMEWORK="10.11"

## Some tools are not directly found by wine
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-ld" "/root/osxcross/target/bin/ld"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-otool" "/root/osxcross/target/bin/otool"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-ranlib" "/root/osxcross/target/bin/ranlib"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-ar" "/root/osxcross/target/bin/ar"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-as" "/root/osxcross/target/bin/as"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin15-install_name_tool" "/root/osxcross/target/bin/install_name_tool"

#### Wine
rm -r /root/osxcross/target/macports/pkgs/opt/local/include/wine/
export C_INCLUDE_PATH="/root/osxcross/target/macports/pkgs/opt/local/include/:/root/osxcross/target/macports/pkgs/opt/local/include/libxml2/:/root/vkd3d/include/"
export LIBRARY_PATH="/root/osxcross/target/macports/pkgs/opt/local/lib"

#### 32bits
export CC="clang-7 -mwine32 -O3 -target x86_64-apple-darwin15 -mlinker-version=0.0 -mmacosx-version-min=10.8 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/ -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks"
## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/x86_64-apple-darwin15-gcc"
chmod +x "/root/osxcross/target/bin/x86_64-apple-darwin15-gcc"
echo '$CC "$@"' > "/root/osxcross/target/bin/i386-apple-darwin15-gcc"
chmod +x "/root/osxcross/target/bin/i386-apple-darwin15-gcc"

cd "/root/wine-git/"
echo "[STAGE 6/11] Configure 32 bits"
./configure --host i386-apple-darwin15 --prefix="/" --with-wine-tools="/root/wine-tools" LFFLAGS=" -Wl,-rpath,/opt/x11/lib -L/root/osxcross/target/macports/pkgs/opt/local/lib" || exit 7

echo "[STAGE 7/11] Make 32 bits"
make -j 4 || exit 8

echo "[STAGE 8/11] Make install 64 bits"
cd "/root/wine-git/wine64-build/"
make install DESTDIR="/root/wine" || exit 9

echo "[STAGE 9/11] Make install 32 bits"
cd "/root/wine-git/wine32-build/"
make install DESTDIR="/root/wine" || exit 10

## Copying libs
echo "[STAGE 10/11] Copying libs"
cp -d /root/osxcross/target/macports/pkgs/opt/local/lib/*.dylib "/root/wine/lib"
rm /root/wine/lib/libpython2.7.dylib

## Fixing imports
echo "[STAGE 11/11] Fixing imports"
bash /root/fix_imports.sh "/root/wine"

## A dependency is missing for gnutls
cd "/root/wine/lib"
ln -s "libidn.12.dylib" "libidn.11.dylib"

## Make symlinks in /lib64 since wine64 only checks there
cd "/root/wine/lib64"
ln -s ../lib/*.dylib .

echo "[END]"
