#!/bin/bash

##### WINE
cd /root/hangover
rm -r wine
ln -s /root/wine-git ./wine

mkdir -p /root/hangover/build/wine-tools
cd /root/hangover/build/wine-tools
../../wine/configure CC="clang" CXX="clang++" --disable-option-checking --disable-tests --without-unwind --enable-win64  >>/dev/null 2>&1
make __tooldeps__ -j 4

#echo "[STAGE 3/11] Installing vkd3d"
#bash "/root/install_vkd3d.sh" "$VKD3D"

##### Cross environment
export LDFLAGS="-Wl,-rpath,@loader_path/../ -Wl,-rpath,/opt/local/lib -Wl,-rpath,/opt/X11/lib/"

mkdir -p /root/hangover/build/wine-host
cd /root/hangover/build/wine-host
../../wine/configure --enable-win64 --host x86_64-apple-darwin17 --prefix="" --with-wine-tools="/root/hangover/build/wine-tools"
make -j4
ln -s /root/hangover/build/wine-host /root/wine
make install DESTDIR="/root/wine"
touch /root/hangover/build/wine-host/.built

mkdir -p /root/hangover/build/wine-guest
cd /root/hangover/build/wine-guest
export C_INCLUDE_PATH="/root/hangover-build/x86_64-w64-mingw32/include/:/root/hangover-build/x86_64-w64-mingw32/include/libxml2/"
export LIBRARY_PATH="/root/hangover-build/x86_64-w64-mingw32/lib:/root/hangover-build/x86_64-w64-mingw32/bin"
export LDFLAGS="-L/root/hangover-build/x86_64-w64-mingw32/lib -L/root/hangover-build/x86_64-w64-mingw32/bin -lxml2"
../../wine/configure --disable-tests --host=x86_64-w64-mingw32 --with-wine-tools=../wine-tools --without-freetype --with-xml --with-xslt ac_cv_lib_soname_xslt="libxslt-1.dll"
make -j 4
make install DESTDIR="/root/hangover-build/x86_64-w64-mingw32/"

mkdir -p /root/hangover/build/wine-guest32
cd /root/hangover/build/wine-guest32
export C_INCLUDE_PATH="/root/hangover-build/i686-w64-mingw32/include/:/root/hangover-build/i686-w64-mingw32/include/libxml2/"
export LIBRARY_PATH="/root/hangover-build/i686-w64-mingw32/lib:/root/hangover-build/i686-w64-mingw32/bin"
export LDFLAGS="-L/root/hangover-build/i686-w64-mingw32/lib -L/root/hangover-build/i686-w64-mingw32/bin -lxml2"
../../wine/configure --disable-tests --host=i686-w64-mingw32 --with-wine-tools=../wine-tools --without-freetype --with-xml --with-xslt ac_cv_lib_soname_xslt="libxslt-1.dll"
make -j 4
make install DESTDIR="/root/hangover-build/i686-w64-mingw32/"

mkdir -p /root/hangover/build/qemu


ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-ld" "/root/osxcross/target/bin/ld"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-otool" "/root/osxcross/target/bin/otool"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-ranlib" "/root/osxcross/target/bin/ranlib"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-ar" "/root/osxcross/target/bin/ar"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-as" "/root/osxcross/target/bin/as"
ln -s "/root/osxcross/target/bin/x86_64-apple-darwin17-install_name_tool" "/root/osxcross/target/bin/install_name_tool"

export CC="clang -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.9 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$MACOSX_DEPLOYMENT_TARGET.sdk/  -F/opt/local/Library/Frameworks"

mkdir -p /root/hangover/bin/
touch /root/hangover/bin/Rez
chmod +x /root/hangover/bin/Rez
touch /root/hangover/bin/SetFile
chmod +x /root/hangover/bin/SetFile

omp install glib2-devel

cat << EOF > /root/hangover/bin/qemugcc
#!/bin/bash
export CC="clang -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.9 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$MACOSX_DEPLOYMENT_TARGET.sdk/  -F/opt/local/Library/Frameworks"
/root/hangover/build/wine-tools/tools/winegcc/winegcc -b x86_64-apple-darwin17  -B/root/hangover/build/wine-tools/tools/winebuild/ -I/root/hangover/build/wine-tools/include/ -I/root/hangover/wine/include -lpthread -DWINE_NOWINSOCK -I/opt/local/include/glib-2.0/ -I/root/hangover/glib/glib/ -L/opt/local/lib --sysroot=/root/hangover/build/wine-host/ "\$@"
EOF
chmod +x /root/hangover/bin/qemugcc


cat << EOF > /root/hangover/bin/qemug++
#!/bin/bash
export CC="clang -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.9 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$MACOSX_DEPLOYMENT_TARGET.sdk/  -F/opt/local/Library/Frameworks"
export CXX="clang -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.9 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$MACOSX_DEPLOYMENT_TARGET.sdk/  -F/opt/local/Library/Frameworks"
/root/hangover/build/wine-tools/tools/winegcc/wineg++ -b x86_64-apple-darwin17 -B/root/hangover/build/wine-tools/tools/winebuild -I/root/hangover/build/wine-tools/include -I/root/hangover/wine/include -lpthread -DWINE_NOWINSOCK -I/opt/local/include/glib-2.0/ -I/root/hangover/glib/glib/ --sysroot=/root/hangover/build/wine-host/ -L/opt/local/lib "\$@"
EOF
chmod +x /root/hangover/bin/qemug++

cat << EOF > /root/hangover/bin/dllgcc
#!/bin/bash
export CC="clang -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.9 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$MACOSX_DEPLOYMENT_TARGET.sdk/  -F/opt/local/Library/Frameworks"
/root/hangover/build/wine-tools/tools/winegcc/winegcc -b x86_64-apple-darwin17  -B/root/hangover/build/wine-tools/tools/winebuild/ -I/root/hangover/build/wine-host/include/ -I/root/hangover/wine/include --sysroot=/root/hangover/build/wine-host/ "\$@"
EOF
chmod +x /root/hangover/bin/dllgcc

export PATH="/root/hangover/bin:$PATH"

cd "/root/hangover/build/qemu"
CC="qemugcc" CXX="qemug++" ../../qemu/configure --disable-bzip2 --disable-libusb --disable-sdl --disable-snappy --disable-virtfs --disable-opengl --python=/usr/bin/python2.7 --disable-xen --disable-lzo --disable-qom-cast-debug --disable-vnc --disable-seccomp --disable-strip --disable-hax --disable-gnutls --disable-nettle --disable-replication --disable-tpm --disable-gtk --disable-gcrypt --disable-linux-aio --disable-system --disable-tools --disable-linux-user --disable-guest-agent --enable-windows-user --disable-fdt --disable-capstone
make -j4

mkdir -p x86_64-windows-user/qemu_guest_dll64
mkdir -p x86_64-windows-user/qemu_host_dll64
mkdir -p x86_64-windows-user/qemu_guest_dll32
mkdir -p x86_64-windows-user/qemu_host_dll32

cd /root/hangover

export C_INCLUDE_PATH="/opt/local/include/:/opt/local/include/libxml2/:/root/vkd3d/include/"
export LIBRARY_PATH="/opt/local/lib:/root/wine"

make -f Makefile.macoscross
cp /usr/lib/gcc/i686-w64-mingw32/6.3-win32/libgcc_s_sjlj-1.dll /root/hangover/build/qemu/x86_64-windows-user/qemu_guest_dll32

mkdir -p /root/wine/hangover
cp -a /root/hangover/build/qemu/x86_64-windows-user/qemu_* /root/wine/hangover/
cp -a /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe* /root/wine/hangover

cp /root/hangover/run_wine.sh /root/wine/bin/wine
chmod +x /root/wine/bin/wine
