#!/bin/bash
export CFLAGS="-O3"
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib/"

cd "/root/wine-git"
mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"

### 64bits build
echo "[STAGE 1/7] Configure 64 bits"
cd "/root/wine-git/wine64-build/"
../configure --enable-win64 --prefix="/"  LFFLAGS="-L/usr/local/lib"  || exit 4

echo "[STAGE 2/7] Make 64 bits"
make -j 4 || exit 5

### 32bits build
echo "[STAGE 3/7] Installing 32 bits dependencies"

/root/install_32bits_dependencies.sh
echo "[STAGE 4/7] Configure 32 bits"
cd "/root/wine-git/wine32-build/"
../configure --with-wine64=/root/wine-git/wine64-build --prefix="/" || exit 6

echo "[STAGE 5/7] Make 32 bits"
make -j 4 || exit 7

echo "[STAGE 6/7] Make install 64 bits"
cd "/root/wine-git/wine64-build/"
make install DESTDIR="/root/wine" || exit 8

echo "[STAGE 7/7] Make install 32 bits"
cd "/root/wine-git/wine32-build/"
make install DESTDIR="/root/wine" || exit 9
echo "[END]"