#!/bin/bash
cp -a "/root/wine-git" "/root/wine-tools" || exit 1

####### Build Tools
echo "[STAGE 1/9] Configure tools"
cd "/root/wine-tools"
./configure || exit 2

echo "[STAGE 2/9] Make tools"
make __tooldeps__ -j 4 || exit 3

####### Build wine
### Environment preparation
mkdir -p "/root/wine-git/wine64-build/"
mkdir -p "/root/wine-git/wine32-build/"

export PATH=${PATH}:/usr/cross-freebsd/bin
export LD_LIBRARY_PATH=/usr/cross-freebsd/lib

#### 64bits
export CFLAGS="-O3"

cd "/root/wine-git/wine64-build/"
echo "[STAGE 4/9] Configure 64 bits"
../configure --enable-win64 --host=x86_64-pc-freebsd12 --prefix=/usr/cross-freebsd --with-wine-tools="/root/wine-tools" || exit 5
echo "[STAGE 5/9] Make 64 bits"
make -j 4 || exit 6

#### 32bits
export CFLAGS="-03"

cd "/root/wine-git/wine32-build/"
echo "[STAGE 6/9] Configure 32 bits"
../configure --with-wine64=/root/wine-git/wine64-build --host=i386-pc-freebsd12 --prefix=/usr/cross-freebsd --with-wine-tools="/root/wine-tools"
echo "[STAGE 7/9] Make 32 bits"
make -j 4 || exit 8

echo "[STAGE 8/9] Make install 64 bits"
cd "/root/wine-git/wine64-build/"
make install DESTDIR="/root/wine" || exit 9

echo "[STAGE 9/9] Make install 32 bits"
cd "/root/wine-git/wine32-build/"
make install DESTDIR="/root/wine" || exit 10
